Add datacenter id in FoundationDBClient, so that we can tell YCSB which DC to talk to.
sears/YCSB pull request #1
Opened 2021-05-25 23:20 UTC by RenxuanW

2021-05-27 22:46 UTC, sears requested changes

2021-05-27 22:46 UTC, sears commented on foundationdb/src/main/java/site/ycsb/db/foundationdb/FoundationDBClient.java
> +  private static final String DATACENTER_ID_DEFAULT = "primary";
You need to modify the 2012 - 2016 copyright header to read 2012 - 2021.

2021-05-27 22:46 UTC, sears commented on foundationdb/src/main/java/site/ycsb/db/foundationdb/FoundationDBClient.java
> +  private static final String DATACENTER_ID_DEFAULT = "primary";
The commit message should start with [foundationdb]

See: https://github.com/brianfrankcooper/YCSB/blob/master/CONTRIBUTING.md

(probably run checkstyle too, unless you already did -- the directions are in that link)

2021-05-27 22:46 UTC, sears commented on foundationdb/src/main/java/site/ycsb/db/foundationdb/FoundationDBClient.java
> +      db.options().setDatacenterId(datacenterId);
We should default datacenterId to "", and change this to:
```java
if (!datacenterId.equals("")) {
//...
}
```
so this doesn't cause trouble for non-HA setups.

2021-05-28 20:12 UTC, xumengpanda approved these changes

2021-05-29 00:46 UTC, merged